export const GET_ALL_VACCINATION_SITE = "GET_ALL_VACCINATION_SITE"
export const CREATE_VACCINATION_SITE = "CREATE_VACCINATION_SITE"
export const EDIT_VACCINATION_SITE = "EDIT_VACCINATION_SITE"
export const DELETE_VACCINATION_SITE = "DELETE_VACCINATION_SITE"